import getSite, { getTemplateConfig } from "@/lib/api";
import "../../globals.css";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { getFont, getAllFontVariables } from "@/lib/fonts";
import { readFile } from "fs/promises";
import path from "path";
import { LayoutPageRenderer } from "@/components/sections/_renderer/PageRenderer";
import { resolvePortfolioConfig, emptyUserConfig } from "@/templates/merge";
import { getTemplate } from "@/templates/registry";
import { LivePreviewProvider } from "@/components/preview/LivePreviewProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

/**
 * Reads a single theme CSS file from disk and returns its contents.
 */
async function loadThemeCSS(slug: string): Promise<string> {
    const baseSlug = slug.endsWith("-dark") ? slug.slice(0, -5) : slug;
    const cssPath = path.join(
        process.cwd(),
        "src",
        "themes",
        `${baseSlug}.css`
    );

    try {
        return await readFile(cssPath, "utf-8");
    } catch {
        console.warn(`Theme CSS file not found: ${cssPath}`);
        if (baseSlug !== "default") {
            const fallbackPath = path.join(
                process.cwd(),
                "src",
                "themes",
                "default.css"
            );
            try {
                return await readFile(fallbackPath, "utf-8");
            } catch {
                return "";
            }
        }
        return "";
    }
}

export default async function DomainLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ domain: string }>;
}>) {
    const { domain } = await params;
    const siteData = await getSite(domain);

    console.log("siteData::", siteData);

    // Get configuration from site data or use defaults
    const colorThemeSlug = siteData?.theme || "default";
    const templateSlug = siteData?.template || "default";
    const fontSlug = siteData?.font || "inter"; // changed default to inter
    const selectedFont = getFont(fontSlug);

    if (!siteData || siteData.error) {
        const SiteNotFoundComponent = (await import("@/app/sites/not-found"))
            .default;
        return (
            <ThemeProvider
                attribute="class"
                defaultTheme="default"
                enableSystem={false}
                disableTransitionOnChange
            >
                <SiteNotFoundComponent />
            </ThemeProvider>
        );
    }

    // 1. Fetch user's template config (or use defaults if missing/preview)
    const rawConfig = await getTemplateConfig(domain);
    const templateDef = getTemplate(templateSlug);
    
    const userConfig = rawConfig && !rawConfig.error ? {
        templateKey: templateSlug,
        themeKey: colorThemeSlug,
        fontKey: fontSlug,
        templateVersion: rawConfig.template_version || '1.0.0',
        overrides: rawConfig.config_overrides || { layout: {}, pages: {} },
        additions: rawConfig.config_additions || { layout: [], pages: {} },
        removals: rawConfig.config_removals || { layout: [], pages: {} },
        ordering: rawConfig.config_ordering || {},
    } : emptyUserConfig(templateSlug, colorThemeSlug, fontSlug, templateDef.version);

    // 2. Resolve the config (SSR merge)
    const resolvedConfig = resolvePortfolioConfig(templateDef, userConfig);

    // 3. Get the selected font configuration
    const allFontVariables = getAllFontVariables();

    // 4. Load only this site's theme CSS
    const themeCSS = await loadThemeCSS(colorThemeSlug);

    return (
        <html lang="en" className={`${allFontVariables} ${colorThemeSlug}`}>
            <head>
                {/* Inject only the active theme's CSS */}
                <style
                    dangerouslySetInnerHTML={{ __html: themeCSS }}
                    data-theme={colorThemeSlug}
                />
            </head>
            <body
                className={`antialiased font-${fontSlug}`}
                style={{
                    fontFamily: `var(${selectedFont.variable})`
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={colorThemeSlug}
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <LivePreviewProvider
                        templateDef={templateDef}
                        initialUserConfig={userConfig}
                        initialLayoutSections={resolvedConfig.layout}
                        siteData={siteData}
                    >
                        {children}
                    </LivePreviewProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
