import getSite, { getTemplateConfig } from "@/lib/api";
import "../../globals.css";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import Script from "next/script";
import { ThemeProvider } from "next-themes";
import { getFont, getAllFontVariables } from "@/lib/fonts";
import { readFile } from "fs/promises";
import path from "path";
import { LayoutPageRenderer } from "@/components/sections/_renderer/PageRenderer";
import { resolvePortfolioConfig } from "@/templates/merge";
import { getTemplate } from "@/templates/registry";
import { userConfigFromRaw } from "@/templates/config";
import { LivePreviewProvider } from "@/components/preview/LivePreviewProvider";
import { THEMES_META } from "@/lib/themes-meta";

const allThemes = THEMES_META.flatMap(t => [t.slug, `${t.slug}-dark`]);

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

/**
 * Reads a single theme CSS file from disk and returns its contents.
 */
async function loadThemeCSS(slug: string): Promise<string> {
    const baseSlug = slug.endsWith("-dark") ? slug.slice(0, -5) : slug;
    const cssPath = path.join(
        process.cwd(),
        "src",
        "themes",
        `${baseSlug}.css`
    );

    try {
        return await readFile(cssPath, "utf-8");
    } catch {
        console.warn(`Theme CSS file not found: ${cssPath}`);
        if (baseSlug !== "default") {
            const fallbackPath = path.join(
                process.cwd(),
                "src",
                "themes",
                "default.css"
            );
            try {
                return await readFile(fallbackPath, "utf-8");
            } catch {
                return "";
            }
        }
        return "";
    }
}

export default async function DomainLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ domain: string }>;
}>) {
    const { domain } = await params;
    const siteData = await getSite(domain);

    console.log("siteData::", siteData);

    // Get configuration from site data or use defaults
    const colorThemeSlug = siteData?.theme || "default";
    const templateSlug = siteData?.template || "default";
    const fontSlug = siteData?.font || "inter"; // changed default to inter
    const selectedFont = getFont(fontSlug);

    if (!siteData || siteData.error) {
        const SiteNotFoundComponent = (await import("@/app/sites/not-found"))
            .default;
        return (
            <ThemeProvider
                attribute="class"
                defaultTheme="default"
                themes={allThemes}
                enableSystem={false}
                disableTransitionOnChange
            >
                <SiteNotFoundComponent />
            </ThemeProvider>
        );
    }

    // 1. Fetch user's template config (or use defaults if missing/preview)
    const rawConfig = await getTemplateConfig(domain);
    const templateDef = getTemplate(templateSlug);
    
    const userConfig = userConfigFromRaw(rawConfig, templateDef, {
        templateKey: templateSlug,
        themeKey: colorThemeSlug,
        fontKey: fontSlug,
    });

    // 2. Resolve the config (SSR merge)
    const resolvedConfig = resolvePortfolioConfig(templateDef, userConfig);

    // 3. Get the selected font configuration
    const allFontVariables = getAllFontVariables();

    // 4. Load only this site's theme CSS
    const themeCSS = await loadThemeCSS(colorThemeSlug);

    return (
        <html lang="en" className={`${allFontVariables} ${colorThemeSlug}`}>
            <head>
                {/* Inject only the active theme's CSS */}
                <style
                    dangerouslySetInnerHTML={{ __html: themeCSS }}
                    data-theme={colorThemeSlug}
                />
                {resolvedConfig.themeOverrides && Object.keys(resolvedConfig.themeOverrides).length > 0 && (
                    <style dangerouslySetInnerHTML={{
                        __html: `:root {
                            ${Object.entries(resolvedConfig.themeOverrides)
                                .filter(([_, v]) => v)
                                .map(([k, v]) => `${k}: ${v};`)
                                .join('\n                            ')}
                        }`
                    }} />
                )}
            </head>
            <body
                className={`antialiased font-${fontSlug}`}
                style={{
                    fontFamily: `var(${selectedFont.variable})`
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={colorThemeSlug}
                    themes={allThemes}
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <LivePreviewProvider
                        templateDef={templateDef}
                        initialUserConfig={userConfig}
                        initialLayoutSections={resolvedConfig.layout}
                        siteData={siteData}
                    >
                        {children}
                    </LivePreviewProvider>
                </ThemeProvider>

                {/* Analytics & Tracking Scripts */}
                {siteData.seo?.google_tag_manager_id && (
                    <Script
                        id="gtm-script"
                        strategy="afterInteractive"
                        dangerouslySetInnerHTML={{
                            __html: `
                            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                            })(window,document,'script','dataLayer','${siteData.seo.google_tag_manager_id}');
                            `
                        }}
                    />
                )}
                {siteData.seo?.google_analytics_id && (
                    <>
                        <Script
                            strategy="afterInteractive"
                            src={`https://www.googletagmanager.com/gtag/js?id=${siteData.seo.google_analytics_id}`}
                        />
                        <Script
                            id="ga4-script"
                            strategy="afterInteractive"
                            dangerouslySetInnerHTML={{
                                __html: `
                                window.dataLayer = window.dataLayer || [];
                                function gtag(){dataLayer.push(arguments);}
                                gtag('js', new Date());
                                gtag('config', '${siteData.seo.google_analytics_id}');
                                `
                            }}
                        />
                    </>
                )}
                {siteData.seo?.facebook_pixel_id && (
                    <Script
                        id="fb-pixel-script"
                        strategy="afterInteractive"
                        dangerouslySetInnerHTML={{
                            __html: `
                            !function(f,b,e,v,n,t,s)
                            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                            n.queue=[];t=b.createElement(e);t.async=!0;
                            t.src=v;s=b.getElementsByTagName(e)[0];
                            s.parentNode.insertBefore(t,s)}(window, document,'script',
                            'https://connect.facebook.net/en_US/fbevents.js');
                            fbq('init', '${siteData.seo.facebook_pixel_id}');
                            fbq('track', 'PageView');
                            `
                        }}
                    />
                )}
            </body>
        </html>
    );
}
